---
apiVersion: v1
kind: Pod
metadata:
  name: loki-pod
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki-pod
spec:
  containers:
  - name: loki-pod
    image: grafana/loki:v0.2.0
    env:
      - name: GRAFANA_ADDR
        value: http://loki:3100

          