$ANSIBLE_VAULT;1.1;AES256
36613236616232373636316563666335663531313865656438303061346564636163386139346132
3363306230656263626361336234303466333430613065310a623335303439366465336136663261
38633534346262306365323265343336616366343830343065386432343531376362323338356365
6563336439306639640a396531343365656536643365333438623239353232643338366262613165
33616233313235333435366230303262663030636666333332623464346466393137316136376262
35623063653964306634363764643936626435396437333166303731646137656233643962373238
64616335363237613163356630356433363361663333313861666164653064383039613566323064
31653565393331636466
