apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: to-do-namespace
  labels:
    app: todo-app
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - name: http
      port: 80          # Service port (inside the cluster)
      targetPort: 80  # FastAPI container port
      nodePort: 30080   # Port exposed on each EC2 worker node (must be 30000â€“32767)